version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - "5200:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: 123
        MYSQL_USER: test
        MYSQL_PASSWORD: 123
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"